
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Jun 23 11:50:41 CEST 2018
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 9;
  public static final int MENOS = 11;
  public static final int AND = 5;
  public static final int NUMR = 20;
  public static final int OR = 6;
  public static final int IGUAL = 16;
  public static final int MAYI = 14;
  public static final int NOT = 7;
  public static final int NXT = 3;
  public static final int TRUE = 21;
  public static final int POR = 18;
  public static final int MEN = 13;
  public static final int NUM = 24;
  public static final int EOF = 0;
  public static final int DIV = 19;
  public static final int MENI = 15;
  public static final int PAP = 8;
  public static final int FALSE = 22;
  public static final int error = 1;
  public static final int BOOL = 25;
  public static final int MAY = 12;
  public static final int ASIG = 4;
  public static final int VAR = 23;
  public static final int MAS = 10;
  public static final int DIST = 17;
  public static final int SEC = 2;
}

