
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue May 08 10:54:13 CEST 2018
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 15;
  public static final int MENOS = 17;
  public static final int AND = 8;
  public static final int NUMR = 11;
  public static final int IGUAL = 22;
  public static final int OR = 9;
  public static final int MAYI = 20;
  public static final int NOT = 10;
  public static final int NXT = 3;
  public static final int TRUE = 12;
  public static final int POR = 24;
  public static final int MEN = 19;
  public static final int NUM = 4;
  public static final int EOF = 0;
  public static final int DIV = 25;
  public static final int MENI = 21;
  public static final int PAP = 14;
  public static final int FALSE = 13;
  public static final int error = 1;
  public static final int BOOL = 5;
  public static final int MAY = 18;
  public static final int ASIG = 7;
  public static final int VAR = 6;
  public static final int MAS = 16;
  public static final int DIST = 23;
  public static final int SEC = 2;
}

