/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asint;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAR = 1;
  /** RegularExpression Id. */
  int LETRA = 2;
  /** RegularExpression Id. */
  int DIG = 3;
  /** RegularExpression Id. */
  int NUM = 4;
  /** RegularExpression Id. */
  int BOOL = 5;
  /** RegularExpression Id. */
  int TRUE = 6;
  /** RegularExpression Id. */
  int FALSE = 7;
  /** RegularExpression Id. */
  int NUMR = 8;
  /** RegularExpression Id. */
  int DEC = 9;
  /** RegularExpression Id. */
  int EX = 10;
  /** RegularExpression Id. */
  int SIGNO = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int OR = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int MAS = 15;
  /** RegularExpression Id. */
  int MENOS = 16;
  /** RegularExpression Id. */
  int DIV = 17;
  /** RegularExpression Id. */
  int POR = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<VAR>",
    "<LETRA>",
    "<DIG>",
    "\"num\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "<NUMR>",
    "<DEC>",
    "<EX>",
    "<SIGNO>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"mas\"",
    "\"menos\"",
    "\"div\"",
    "\"por\"",
    "<token of kind 19>",
    "\"&&\"",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"*\"",
    "\"/\"",
  };

}
