/* Generated By:JavaCC: Do not edit this line. EvaluadorConstants.java */
package javaCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EvaluadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETRA = 1;
  /** RegularExpression Id. */
  int DIG = 2;
  /** RegularExpression Id. */
  int SIGNO = 3;
  /** RegularExpression Id. */
  int NUM = 4;
  /** RegularExpression Id. */
  int BOOL = 5;
  /** RegularExpression Id. */
  int TRUE = 6;
  /** RegularExpression Id. */
  int FALSE = 7;
  /** RegularExpression Id. */
  int SEC = 8;
  /** RegularExpression Id. */
  int ANDT = 9;
  /** RegularExpression Id. */
  int ORT = 10;
  /** RegularExpression Id. */
  int NOTT = 11;
  /** RegularExpression Id. */
  int DEC = 12;
  /** RegularExpression Id. */
  int EX = 13;
  /** RegularExpression Id. */
  int VAR = 16;
  /** RegularExpression Id. */
  int PDEC = 17;
  /** RegularExpression Id. */
  int PEXP = 18;
  /** RegularExpression Id. */
  int LENT = 19;
  /** RegularExpression Id. */
  int LDEC = 20;
  /** RegularExpression Id. */
  int LEXP = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LETRA>",
    "<DIG>",
    "<SIGNO>",
    "\"num\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"&&\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "<DEC>",
    "<EX>",
    "<token of kind 14>",
    "<token of kind 15>",
    "<VAR>",
    "<PDEC>",
    "<PEXP>",
    "<LENT>",
    "<LDEC>",
    "<LEXP>",
    "\";\"",
    "\"=\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"*\"",
    "\"/\"",
  };

}
