/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asint;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETRA = 1;
  /** RegularExpression Id. */
  int DIG = 2;
  /** RegularExpression Id. */
  int NUM = 3;
  /** RegularExpression Id. */
  int BOOL = 4;
  /** RegularExpression Id. */
  int TRUE = 5;
  /** RegularExpression Id. */
  int FALSE = 6;
  /** RegularExpression Id. */
  int DEC = 7;
  /** RegularExpression Id. */
  int EX = 8;
  /** RegularExpression Id. */
  int SIGNO = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int MAS = 13;
  /** RegularExpression Id. */
  int MENOS = 14;
  /** RegularExpression Id. */
  int DIV = 15;
  /** RegularExpression Id. */
  int POR = 16;
  /** RegularExpression Id. */
  int VAR = 18;
  /** RegularExpression Id. */
  int PDEC = 19;
  /** RegularExpression Id. */
  int PEXP = 20;
  /** RegularExpression Id. */
  int LENT = 21;
  /** RegularExpression Id. */
  int LDEC = 22;
  /** RegularExpression Id. */
  int LEXP = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LETRA>",
    "<DIG>",
    "\"num\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "<DEC>",
    "<EX>",
    "<SIGNO>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"mas\"",
    "\"menos\"",
    "\"div\"",
    "\"por\"",
    "<token of kind 17>",
    "<VAR>",
    "<PDEC>",
    "<PEXP>",
    "<LENT>",
    "<LDEC>",
    "<LEXP>",
    "\"&&\"",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"*\"",
    "\"/\"",
  };

}
